### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by zarankumar** [CodeCabin/plugin-deactivation-survey#2]
i m testing the plugin as per documentation. But form is not triggering. is this still working?

**Comment by DylanCodeCabin** [comment]
Hi @zarankumar 

Thank you for reaching out, we do appreciate it.

The deactivation survey is no longer active within our plugins, it may be enabled again in future, however, for the time being, it is no longer active.

This repo is available for informative purposes only, and most likely will not function out of the box.
